name: competition
channels:
  - conda-forge
dependencies:
  - cython=0.29.20
  - gsl=2.6
  - matplotlib=3.3.1
  - numpy=1.19.1
  - pandas=1.1.0
  - pytest=5.3.1
  - python=3.6
  - scipy=1.5.2
  - seaborn=0.9.0
  - cythongsl=0.2.2
  - treelib=1.6.1

