algorithm: "WF"
times:
  division_rate: 1
  max_time: 10
  samples: 100
population:
  initial_cells: 100
fitness:
  initial_fitness_array: 1  # For initial clones. Integers be converted to a list
  mutation_rates: 0
labels:
  initial_label_array: 0   # For initial clones. Integers be converted to a list
treatment:
  treatment_timings: [5, 7]
  treatment_effects: [[1], [2]]
differentiated_cells:
  stratification_sim_proportion: 1
plotting:
  figsize: [10, 10]

